### ISSUE TITLE
Changing name of a structure

### ISSUE THREAD

**Issue by adrimbarean** [coccinelle/coccinelle#128]
I am trying to change the names of the structures in my code according to linux coding style and I am using the following code with Python script to do it:
```
@rule1 disable all@
type t;
@@
typedef struct {
...
} t;

@ script:python foo @
t_fixed;
var;
t << rule1.t;
@@
import re
def split_uppercase(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

print t
coccinelle.t_fixed = split_uppercase(t)
print coccinelle.t_fixed
coccinelle.var = cocci.make_type(t_fixed)
print var

@rule2 disable all@
type rule1.t;
type foo.var;
@@
+ var
- t
```
For example, I want the code: 
```
typedef struct {
	char me;
	long you;
} structExample;

int main (void) {
	structExample *DeV;
	return 0;
}
```
To become:
```
typedef struct {
	char me;
	long you;
} struct_example;

int main (void) {
	struct_example *DeV;
	return 0;
}
```
But I am getting the following message:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
>  -----------------------------------------------------------------------
> processing semantic patch file: structs_test.cocci
> with isos from: /usr/lib/coccinelle/standard.iso
>  -----------------------------------------------------------------------
> 
> dependencies for script satisfied:
> HANDLING: test_basic.c
> dependencies for rule rule1 satisfied:
>      transformation info is empty
> dependencies for script satisfied:
> Traceback (most recent call last):
>   File "<string>", line 10, in <module>
> AttributeError: Cocci instance has no attribute 'make_type'
> while running simple python string:
> from coccinelle import *
> 
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
> 
> print t
> coccinelle.t_fixed = split_uppercase(t)
> print coccinelle.t_fixed
> coccinelle.var = cocci.make_type(t_fixed)
> print var
> 
> 
> 
> 
> 
> 
> 
> :
> Failure in foo
> Fatal error: exception Yes_pycocci.Pycocciexception

I am sorry if I am not posing the question correctly. I am new to Github and have a lot to learn. Thank you for all the hard work with this tool.

**Comment by JuliaLawall** [comment]
On Wed, 3 Jan 2018, Andrei Drimbarean wrote:

>
> I am trying to change the names of the structures in my code according to linux coding style and I am using the following code with Python script to do it:
>
> @rule1 disable all@
> type t;
> @@
> typedef struct {
> ...
> } t;
>
> @ script:python foo @
> t_fixed;
> var;
> t << rule1.t;
> @@
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
>
> print t
> coccinelle.t_fixed = split_uppercase(t)
> print coccinelle.t_fixed
> coccinelle.var = cocci.make_type(t_fixed)
> print var
>
> @rule2 disable all@
> type rule1.t;
> type foo.var;
> @@
> + var
> - t
>
> For example, I want the code:
>
> typedef struct {
> 	char me;
> 	long you;
> } structExample;
>
> int main (void) {
> 	structExample *DeV;
> 	return 0;
> }
>
> To become:
>
> typedef struct {
> 	char me;
> 	long you;
> } struct_example;
>
> int main (void) {
> 	struct_example *DeV;
> 	return 0;
> }
>
> But I am getting the following message:
>
> INIT_DEFS_BUILTINS: /USR/LIB/COCCINELLE/STANDARD.H
>
> PROCESSING SEMANTIC PATCH FILE: STRUCTS_TEST.COCCI
> WITH ISOS FROM: /USR/LIB/COCCINELLE/STANDARD.ISO
>
>       dependencies for script satisfied:
>       HANDLING: test_basic.c
>       dependencies for rule rule1 satisfied:
>       transformation info is empty
>       dependencies for script satisfied:
>       Traceback (most recent call last):
>       File "", line 10, in
>       AttributeError: Cocci instance has no attribute 'make_type'
>       while running simple python string:
>       from coccinelle import *
>
>       import re
>       def split_uppercase(s):
>       return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
>
>       print t
>       coccinelle.t_fixed = split_uppercase(t)
>       print coccinelle.t_fixed
>       coccinelle.var = cocci.make_type(t_fixed)
>       print var
>
>       :
>       Failure in foo
>       Fatal error: exception Yes_pycocci.Pycocciexception
>
> I am sorry if I am not posing the question correctly. I am new to Github and have a lot to learn. Thank you for all the hard work with this tool.

Hello,

First a small point, please post to the Coccinelle mailing list instead:
cocci@systeme.lip6.fr

Another small point, The Linux kernel frowns on typedefs for structs.  So
really you want to turn it into

struct example
   char me;
   long you;
} struct_example;

int main (void) {
      struct example *DeV;
      ...
}

But in the end I don't know why make_type is not working.  It looks like
it is supported.  I will check with my engineer, who does all of the
python work.

Since in the end you want just an identifier, not a type, you can follow
the model in coccinelle/demos/pythontococci.cocci

julia

**Comment by elfring** [comment]
I can not directly help with a solution for the observed Python traceback.
But I guess that a few details could be adjusted in the shown SmPL rules.
1. How do you think about to use [position variables](http://coccinelle.lip6.fr/docs/main_grammar002.html "Metavariables for transformations") there?
2. Do you need to specify any more context data around the desired changes in “`rule2`”?
3. Would you like to call the method “`make_ident`” (instead of “`make_type`”) in the SmPL rule “`foo`”?

By the way:
Would you dare to try the other supported programming language “OCaml” out for the renaming of identifiers?

**Comment by adrimbarean** [comment]
I have followed the pointers Julia gave me, that is trying to convert the code from using `typedef` to not using it with the following semantic patch:
```
@rule_init@
type t;
@@
typedef struct {
...
} t;

@rule_in@
type rule_init.t;
identifier var;
@@
t var;

@script:python convert@
t << rule_init.t;
idt;
@@
coccinelle.idt = t;

@rule_change@
identifier convert.idt;
type rule_init.t;
@@
- typedef struct
+ struct idt
{ ... }
- t
;

@@
type rule_init.t;
identifier var, convert.idt;
@@
+ struct idt *var;
- t *var;

@@
type rule_init.t;
identifier var, convert.idt;
@@
++ struct idt var;
- t var;

@@
type rule_init.t, funct;
identifier func, var, convert.idt;
parameter list P, Q;
@@
funct func(P,
- t *var
+ struct idt *var
 ,Q){...}

@@
type rule_init.t, funct;
identifier func, var, convert.idt;
parameter list P, Q;
@@
funct func(P,
- t var
+ struct idt var
 ,Q){...}
```
And I received the following result, which is good:

```
--- test_basic.c
+++ /tmp/cocci-output-6381-2c0bb8-test_basic.c
@@ -1,10 +1,12 @@
-typedef struct {
+struct strName {
 	char me;
 	long you;
-} strName;
+};
 
-int main (strName *bar, strName baz) {
-	strName *DeV;
-	strName mama;
+int main (struct strName *bar, struct strName baz) {
+	struct strName *DeV;
+	
+	struct strName mama;
+	
 	return 0;
 }
```
Then I managed to apply the following patch:
```
@rule1@
identifier t;
@@
struct t {
...
};

@ script:python foo @
t_fixed;
t << rule1.t;
@@
import re
def split_uppercase(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

print coccinelle.t
coccinelle.t_fixed = split_uppercase(t)
print coccinelle.t_fixed

@rule2 disable all@
identifier foo.t_fixed, rule1.t;
@@
struct
+ t_fixed
- t
{...};

@rule3 disable all@
identifier foo.t_fixed, rule1.t;
@@
struct
+ t_fixed
- t
```
And successfully got the result: 
```
--- test_basic.c
+++ /tmp/cocci-output-6417-f85c01-test_basic.c
@@ -1,12 +1,12 @@
-struct strName {
+struct str_name {
 	char me;
 	long you;
 };
 
-int main (struct strName *bar, struct strName baz) {
-	struct strName *DeV;
+int main (struct str_name *bar, struct str_name baz) {
+	struct str_name *DeV;
 
-	struct strName mama;
+	struct str_name mama;
 
 	return 0;
 }
```
I do not know if these modifications will be acceptable, but it is a solution and I will present it to my team. Thank you for your help and patience @JuliaLawall ! As for the first point:

> First a small point, please post to the Coccinelle mailing list instead:

I apologize for the inconvenience. Please tell me what to do: should I post this to the mailing list, or just do nothing to avoid any more inconvenience?

I tried to do what @elfring said too and I changed my original patch to:
```
@rule1 disable all@
type t;
position p;
@@
typedef struct { ... } t@p;

@ script:python foo @
t_fixed;
var;
t << rule1.t;
@@
import re
def split_uppercase(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

print t
coccinelle.t_fixed = split_uppercase(t)
print t_fixed
coccinelle.var = cocci.make_ident(t_fixed)
print var

@rule2 disable all@
type rule1.t;
type foo.var;
position rule1.p;
@@
typedef struct
{...}
+ var;
- t@p;
```
And got a similar error:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> \-----------------------------------------------------------------------
> processing semantic patch file: structs_test.cocci
> with isos from: /usr/lib/coccinelle/standard.iso
> \-----------------------------------------------------------------------
> 
> dependencies for script satisfied:
> HANDLING: test_basic.c
> dependencies for rule rule1 satisfied:
>      transformation info is empty
> dependencies for script satisfied:
> Traceback (most recent call last):
>   File "<string>", line 10, in <module>
> AttributeError: Cocci instance has no attribute 'make_ident'
> while running simple python string:
> from coccinelle import *
> 
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
> 
> print t
> coccinelle.t_fixed = split_uppercase(t)
> print t_fixed
> coccinelle.var = cocci.make_ident(t_fixed)
> print var
> 
> :
> Failure in foo
> Fatal error: exception Yes_pycocci.Pycocciexception

But if I change line 19 to `coccinelle.var = t_fixed` i get the following result:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> \-----------------------------------------------------------------------
> processing semantic patch file: structs_test.cocci
> with isos from: /usr/lib/coccinelle/standard.iso
> \-----------------------------------------------------------------------
> 
> dependencies for script satisfied:
> HANDLING: test_basic.c
> dependencies for rule rule1 satisfied:
>      transformation info is empty
> dependencies for script satisfied:
> dependencies for rule rule2 satisfied:
>      transformation info returned:
>           transform state: 1
>      transform one node: 1
> Fatal error: exception Common.Impossible(147)

I will try to use OCaml for the rename function too, but I have to learn how to do that first. Thank you too, @elfring, for help!

**Comment by JuliaLawall** [comment]
>       First a small point, please post to the Coccinelle mailing list
>       instead:
>
> I apologize for the inconvenience. Please tell me what to do: should I post
> this to the mailing list, or just do nothing to avoid any more
> inconvenience?

Doing nothing is fine.  If you have further questions, please try the
mailing list.

> And got a similar error:
>
>       init_defs_builtins: /usr/lib/coccinelle/standard.h
>       -----------------------------------------------------------------------
>       processing semantic patch file: structs_test.cocci
>       with isos from: /usr/lib/coccinelle/standard.iso
>       -----------------------------------------------------------------------
>
>       dependencies for script satisfied:
>       HANDLING: test_basic.c
>       dependencies for rule rule1 satisfied:
>       transformation info is empty
>       dependencies for script satisfied:
>       Traceback (most recent call last):
>       File "", line 10, in
>       AttributeError: Cocci instance has no attribute 'make_ident'

I thought all this was implemented for python as well. I will check on it.

julia

**Comment by thierry-martinez** [comment]
I am not able to reproduce the problem: `make_ident` and `make_type` should be defined in the module `Cocci`.  Could you tell me which version of Python you are using? By the way, you should prefix `t_fixed` by `coccinelle.` in the following line, but that does not explain the error you report.

`coccinelle.var = cocci.make_type(**coccinelle.**t_fixed)`

With this fix, your script works with Python 2.7 and Python 3.6 on my machine.

**Comment by elfring** [comment]
@thierry-martinez: Would you like to explain how the notation “`cocci.make_type(**coccinelle.**t_fixed)`” could matter in such uses cases?

How do you think about to distinguish better between the renaming of identifiers and data type adjustments?

**Comment by elfring** [comment]
@adrimbarean:
I find the following code sequence questionable from your example.

```
@rule1 disable all@
type t;
position p;
@@
typedef struct { ... } t@p;
…
coccinelle.t_fixed = split_uppercase(t)
…
coccinelle.var = cocci.make_ident(t_fixed)
…
```


Which test result would you get for an other statement combination there?

```
@rule1 disable all@
identifier type_name;
position p;
@@
typedef struct { ... } type_name@p;
…
@ script:python foo @
input << rule1.type_name;
var;
@@
…
coccinelle.var = cocci.make_ident(split_uppercase(input))
…
```


How do you think about to move your function “split_uppercase” into [another SmPL initialisation script rule](http://coccinelle.lip6.fr/docs/main_grammar003.html "Metavariables for scripts")?

**Comment by adrimbarean** [comment]
@thierry-martinez I have modified the code to `cocci.make_type(coccinelle.t_fixed)`, but the error prevailes:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> warning: rule2: inherited metavariable type_name not used in the -, +, or context code
> HANDLING: test_basic.c
> Traceback (most recent call last):
>   File "<string>", line 8, in <module>
> AttributeError: Cocci instance has no attribute 'make_type'
> while running simple python string:
> from coccinelle import *
> 
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
> 
> print input
> coccinelle.var = cocci.make_type(coccinelle.t_fixed)
> print var
> 
> :
> Failure in foo
> Fatal error: exception Yes_pycocci.Pycocciexception

I am using Python 2.7.12

**Comment by adrimbarean** [comment]
@elfring I have tried the code:
```
@rule1 disable all@
identifier type_name;
position p;
@@
 typedef struct { ... } type_name@p;

@ script:python foo @
input << rule1.type_name;
var;
@@
import re
def split_uppercase(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

print input
coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
print var

@rule2 disable all@
type rule1.type_name;
type foo.var;
@@
typedef struct
{...}
+ var;
- t;
```
And the result is:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> Fatal error: exception Failure("minus: parse error: \n = File \"structs_test.cocci\", line 5, column 24,  charpos = 85\n    around = 'type_name', whole content =  typedef struct { ... } type_name@p;\r\n")

If I move the function into initialization script:
```
@initialize:python@
@@
import re
def split_uppercase(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
```
And call it:
```
@ script:python foo @
input << rule1.type_name;
var;
@@

print input
coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
print var
```
The same result apears:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> Fatal error: exception Failure("minus: parse error: \n = File \"structs_test.cocci\", line 11, column 24,  charpos = 293\n    around = 'type_name', whole content =  typedef struct { ... } type_name@p;\r\n")

But if I declare `type_name` as `type` the following result occurs:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> warning: rule2: inherited metavariable type_name not used in the -, +, or context code
> HANDLING: test_basic.c
> Traceback (most recent call last):
>   File "<string>", line 5, in <module>
> AttributeError: Cocci instance has no attribute 'make_ident'
> while running simple python string:
> from coccinelle import *
> 
> 
> print input
> coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
> print var
> 
> :
> Failure in foo
> Fatal error: exception Yes_pycocci.Pycocciexception

**Comment by elfring** [comment]
I find the message “minus: parse error” surprising.


>warning: rule2: inherited metavariable type_name not used in the -, +, or context code

I would interpret this information in the way that your evolving SmPL script became temporarily inconsistent.

-----

Can it be that the mentioned approach “`cocci.make_type(coccinelle.t_fixed)`” is just wrong?
* Script variables should be read without the prefix “coccinelle”.
* You would like to construct type names (which are identifiers) somehow.
(“Type strings” will be appropriate at other places.)

**Comment by adrimbarean** [comment]
@elfring Updated rule2. Yes it was inconsistent. And i read input without the "coccinelle." prefix. But the error stays the same:

> init_defs_builtins: /usr/lib/coccinelle/standard.h
> Fatal error: exception Failure("minus: parse error: \n = File \"structs_test.cocci\", line 11, column 24,  charpos = 293\n    around = 'type_name', whole content =  typedef struct { ... } type_name@p;\r\n")

> Can it be that the mentioned approach “cocci.make_type(coccinelle.t_fixed)” is just wrong?

Yes, that is highly probable to be true. As I said before: using Julia's pointers I managed to make a script that converts the structures from using `typedef` to not using it. Then the name of the structure can be processed using only identifiers. But as I see it, using `typedef` actually makes a new type just like `char` or `int` and it can not be matched using an `identifier` metavariable. I could be wrong though.

**Comment by elfring** [comment]
How does the software situtation fit to [the following information](http://en.cppreference.com/w/c/language/typedef "Description for “typedef”")?

```
The typedef declaration provides a way to declare an identifier as a type alias, to be used to replace a possibly complex type name.
```

-----

I get also the message “minus: parse error” with the software combination “Coccinelle 1.0.6-00389-g8436de97 (OCaml 4.05)” for another tiny SmPL script example.

```
@display@
identifier type_name;
@@
 typedef struct { ... }
*type_name;
```


Would @JuliaLawall (or @thierry-martinez) like to explain this “surprise”?

**Comment by JuliaLawall** [comment]
On Fri, 12 Jan 2018, Andrei Drimbarean wrote:

>
> @elfring I have tried the code:
>
> @rule1 disable all@
> identifier type_name;
> position p;
> @@
>  typedef struct { ... } type_name@p;
>
> @ script:python foo @
> input << rule1.type_name;
> var;
> @@
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
>
> print input
> coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
> print var
>
> @rule2 disable all@
> type rule1.type_name;
> type foo.var;
> @@
> typedef struct
> {...}
> + var;
> - t;
>
> And the result is:
>
>       init_defs_builtins: /usr/lib/coccinelle/standard.h
>       Fatal error: exception Failure("minus: parse error: \n = File "structs_test.cocci", line 5, column 24, charpos = 85\n around = 'type_name', whole content = typedef struct { ... } type_name@p;\r\n")
>
> If I move the function into initialization script:
>
> @initialize:python@
> @@
> import re
> def split_uppercase(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
>
> And call it:
>
> @ script:python foo @
> input << rule1.type_name;
> var;
> @@
>
> print input
> coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
> print var
>
> The same result apears:
>
>       init_defs_builtins: /usr/lib/coccinelle/standard.h
>       Fatal error: exception Failure("minus: parse error: \n = File "structs_test.cocci", line 11, column 24, charpos = 293\n around = 'type_name', whole content = typedef struct { ... } type_name@p;\r\n")
>
> But if I declare type_name as type the following result occurs:
>
>       init_defs_builtins: /usr/lib/coccinelle/standard.h
>       warning: rule2: inherited metavariable type_name not used in the -, +, or context code
>       HANDLING: test_basic.c
>       Traceback (most recent call last):
>       File "", line 5, in
>       AttributeError: Cocci instance has no attribute 'make_ident'
>       while running simple python string:
>       from coccinelle import *
>
>       print input
>       coccinelle.var = cocci.make_ident(split_uppercase(coccinelle.input))
>       print var
>
>       :
>       Failure in foo
>       Fatal error: exception Yes_pycocci.Pycocciexception

For me the following works:

@ script:python foo @
input << rule1.type_name;
var;
@@
import re
def split_uppercase(s):
    return
re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz\
", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

print input
coccinelle.var = cocci.make_type(split_uppercase(input))
print coccinelle.var

@rule2 disable all@
type rule1.type_name;
type foo.var;
@@
typedef struct
{...}
+ var;
- type_name;

julia

**Comment by JuliaLawall** [comment]
On Fri, 12 Jan 2018, Markus Elfring wrote:

>
> How does the software situtation fit to the following information?
>
> The typedef declaration provides a way to declare an identifier as a type alias, to be used to replace a possibly complex type name.
>
> __________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
>
> I get also the message “minus: parse error” with the software combination “Coccinelle 1.0.6-00389-g8436de97 (OCaml 4.05)” for another tiny SmPL script example.
>
> @display@
> identifier type_name;
> @@
>  typedef struct { ... }
> *type_name;
>
> Would @JuliaLawall (or @thierry-martinez) like to explain this “surprise”?

There is no surprise.  typedefs end in ;s.  In the - code, your typedef
does not.

julia

**Comment by JuliaLawall** [comment]
On Fri, 12 Jan 2018, Andrei Drimbarean wrote:

>
> @elfring Updated rule2. Yes it was inconsistent. And i read input without the "coccinelle." prefix. But the error stays the same:
>
>       init_defs_builtins: /usr/lib/coccinelle/standard.h
>       Fatal error: exception Failure("minus: parse error: \n = File "structs_test.cocci", line 11, column 24, charpos = 293\n around = 'type_name', whole content = typedef struct { ... } type_name@p;\r\n")
>
>       Can it be that the mentioned approach “cocci.make_type(coccinelle.t_fixed)” is just wrong?
>
> Yes, that is highly probable to be true. As I said before: using Julia's pointers I managed to make a script that converts the structures from using typedef to not using it. Then the name of the structure can be processed using only identifiers. But
> as I see it, using typedef actually makes a new type just like char or int and it can not be matched using an identifier metavariable. I could be wrong though.

A typedef makes a type.

"coccinelle." should not be used when referring to the metavariables
inherited from other rules.

julia

**Comment by elfring** [comment]
>A typedef makes a type.

It seems that we stumble on a disagreement about C language terms and their mapping in your software.

How do you distinguish these items (for the semantic patch language)?
* alias
* [type](http://coccinelle.lip6.fr/docs/main_grammar002.html "Metavariables for transformations")
* type name

**Comment by elfring** [comment]
>typedefs end in ;s. In the - code, your typedef does not.

I can move a semicolon from a questionable position.

```
@SmPL_test@
identifier my_alias;
@@
 typedef struct { ... }
*my_alias
 ;
```


But the Coccinelle software does still not like to show me type definitions from source file examples by the asterisk functionality in this case.

**Comment by elfring** [comment]
>A typedef makes a type.

I can acknowledge that the following SmPL approach produces usable data processing results.

```
@display@
type my_alias;
@@
 typedef struct { ... }
*my_alias
 ;
```


I find it questionable if an identifier should be handled as a type name at this place.

**Comment by elfring** [comment]
The following SmPL script variant produces also usable test results.

```
@initialize:python@
@@
import re
def adjust_string(s):
    return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()

@find_update_candidate disable all@
type my_alias;
position pos;
@@
 typedef struct { ... } my_alias@pos;

@script:python adjustment@
input << find_update_candidate.my_alias;
updated;
@@
coccinelle.updated = cocci.make_type(adjust_string(input))

@replacement disable all@
type adjustment.updated, find_update_candidate.my_alias;
position find_update_candidate.pos;
@@
 typedef struct { ... }
-my_alias@pos
+updated
 ;
```


But I find the role of the metavariable type “`type`” still strange here.

**Comment by JuliaLawall** [comment]
On Fri, 12 Jan 2018, Markus Elfring wrote:

>
> The following SmPL script variant produces also usable test results.
>
> @initialize:python@
> @@
> import re
> def adjust_string(s):
>     return re.sub(r'([a-z-0-9])((?<![0-9]{4})[A-Z])',r'\1_\2',s).replace("_k_Hz", "_kHz").replace("_M_Hz", "_MHz").replace("d_B", "dB").lower()
>
> @find_update_candidate disable all@
> type my_alias;
> position pos;
> @@
>  typedef struct { ... } my_alias@pos;
>
> @script:python adjustment@
> input << find_update_candidate.my_alias;
> updated;
> @@
> coccinelle.updated = cocci.make_type(adjust_string(input))
>
> @replacement disable all@
> type adjustment.updated, find_update_candidate.my_alias;
> position find_update_candidate.pos;
> @@
>  typedef struct { ... }
> -my_alias@pos
> +updated
>  ;
>
> But I find the role of the metavariable type “type” still strange here.

A typedef makes a type.  It make something that you could use to declare a
variable in a function parameter list for example.

julia

**Comment by elfring** [comment]
>A typedef makes a type.

Do you express a view here which is different from [the terminology by the standard specification for the C programming language](http://c0x.coding-guidelines.com/6.7.7.html "Type definitions")?


>It make something that you could use to declare a variable in a function parameter list for example.

Such information is reasonable to some degree. Would you like to distinguish the grammatical items between a function argument and “[the typedef](http://en.cppreference.com/w/c/language/typedef "Typedef declaration")” precisely?

**Comment by vgambier** [comment]
I am closing this issue because it is stale and the issue may have been resolved. If you are still having problems, feel free to leave a comment.
